theme: jekyll-theme-minimal
title: Resources to learn Punjabi (ਪੰਜਾਬੀ) language
og_image: "/assets/images/Punjabi_Alphabet.jpg"
og_image: /assets/images/Punjabi_Alphabet.jpg
logo: /assets/images/Punjabi_Alphabet.jpg


